import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRef, useState } from "react";

import styles from "../styles/Home.module.css";

const Home: NextPage = ({ data }: any) => {
  const inputRef = useRef<HTMLInputElement>(null!);
  const [countries, setCountries] = useState<any[]>(data);

  const findCountryHandler = () => {
    const selectedValue = inputRef.current.value;

    if (selectedValue === "") return setCountries(data);

    const filteredCountries = data.filter((country: any) => {
      if (country.name.common.toLowerCase().includes(selectedValue.toLowerCase())) {
        return country;
      }
    });

    setCountries(filteredCountries);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Countries | Find Your Country!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/earth.png" />
      </Head>

      <div className={styles.find}>
        <label>Find country:</label>
        <input
          placeholder="Germany, Brazil, Peru"
          ref={inputRef}
          onChange={findCountryHandler}
        />
      </div>

      <div className={styles.countries}>
        {countries.map((country: any) => {
          return (
            <Link
              href={`/country/${country.name.common.toLowerCase().replaceAll(" ", "-")}`}
              key={country.name.common}
            >
              <div className={styles.country}>
                <div className={styles.image}>
                  <Image
                    src={country.flags.png}
                    layout="fill"
                    objectFit="cover"
                    priority={true}
                  />
                </div>
                <h3>{country.name.common}</h3>
              </div>
            </Link>
          );
        })}
      </div>
    </div>
  );
};

export default Home;

export const getStaticProps = async () => {
  const response = await fetch(`https://restcountries.com/v3.1/all`);
  const data = await response.json();

  return {
    props: { data },
  };
};
